sudo: false
language: python
matrix:
  include:
    - python: "3.5"
      env: LTD_MASON_BUILD=true
install:
  - pip install -r requirements.txt
  - pip install "ltd-mason>=0.2,<0.3"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd-mason-travis --html-dir _build/html
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="dmtn-082"
    # AWS and LTD Keeper credentials as encrypted secrets here
    - secure: "FW1hUtzp9tlbq1+5Dpb1QQCSQFuDtPpnPQlqAfwOYnV2SsjT+7J1UrRqaXrt19hDOSBqSC7s416tMxZtpmcPOrRmR2xNpXVY9cCdR66I2wnfY7/5/9CX1bsxbiiI1rkM2lCFJ5r0acoQL3Uqe632LziY9xRqhKPlfA2Tz+Fs6ZuMFetRRy54i5VOW6lplysFgJfhu6Fx13fXp7XhND/Yqsb06nNDLphV6BxMwW1RFqnoPQ7DNG2pY1EdezWj6SeUmrHrr+j8iVi0g3YwTszx7fsdk3TfkpAZHeu0+zOauiOSQ/jqZBJFYflVHRopFSRpXmbzE0rVaBph1hmR9T6Ak6Tkf/kja8Hv/bbVMgvYwXnuwlAaOEjrmHdC9z2v18BazYtzIaUCpk2XG+r43ZRkSZiMuMr2owjnJU/y/9sgzyN33D5qPTO2aw5TZpwA90lRDSWEFEUh5HyEMNEKqNTL4xdjIz++ksDe1D8T9W4+SJ96EBGTUX78y0ufPVe3M2GB0UBFTbtxQ1grfc1gXXKlUCpRYCNqTNINmV05rjihSkWPaubgumDHeMGW1Rs9BY4MJ0FNxXRV/eTm/JlfAw7ijOY2CXe7cbf+nXG1cjwfuEBkSBXtvzbHK1VpIuw5oArHiFBcX9loR6uwr/YxXizbcqIdyqGJG2iPPbMYtYa2iSU="
    - secure: "WlFaFzakW1HJMpvS9rqmN+EwwLlgs3MKH68ntPfJHTCzaOw2nvOUY2PrO70eggEIDngCp9L4O+5wIhYFlUxTnM2oH2gQ7QtHui3jUFjz8lDer71eYJZP9AW5UlT0SdxsHXJFUNJh5PTIY6hI5s0gIsBLu3REC1FD9x6Y3gjAdXnVchD/tGDlvRa0bhK9/H6F5nWGjcVccAoeeDrn+WY9klRJE7MAE81f7O+qu7d3Vqd7Q8FAQfdriKeC3g+l66AoQQ0xqH9KfszOAmad60gJwaLycbBRJHqsejysIkR7hV6jxq6051bJNqKuZlwqbjn1wH6LZkkrFszjfaOF+AErXopeiUKpwaSq4tW1OTo6eSTjKcv0SFqNxx4nHBgNToTSKdvY944zuh6c1wFX4M/RVMp1VxidCOZspmY5QQOA79hkalI/R/bZmtWonTm6DvnQOb/x1Hxo6B8Ir2IfOnT9W/HsCH/ybbPWBfU/+0dC7QaTz/AMhajlujgpX3C1EtmIKh2fVkg4g9p/w6qJCmZSIEtCf5eOMrLcu9/83NNHV9hZOGCs6Vg40fqMgKNKiGQnPhhdLZFjkV2Ujf54Bz+bFrl8YhPFNVoDU3kLIv8hYkFPUEqkI+I6kVuaYWMCoIeCCzLDlW6ueSQtdkCkOoHo+V1DeyhHtEQO07fHSzs8/Zg="
